### ISSUE TITLE
Controller crash

### ISSUE THREAD

**Issue by Ashen1994** [danielhoeltgen/Dual-Arm-Robot-Force-Controlled-Object-Manipulation#1]
Hello daniel,I want use your project to control two UR5 arms. I replaced the model of UR10 with the model of UR5. but when I start the dual_arm_robot_bringup_ros_control.launch , one of them can't connect rightly.Could you give me some advice? 
Thank you.

**Comment by danielhoeltgen** [comment]
Sorry for that I'm reading your comment just now. I hope you could already solve the problem. When you change the robot model you also have to change some parameters in the launch files.
