### ISSUE TITLE
Running demo

### ISSUE THREAD

**Issue by AaronZhu2018** [danielhoeltgen/Dual-Arm-Robot-Force-Controlled-Object-Manipulation#3]
Can this project run only in the virtual environment without the real ur5 controller input?
I want to try and learn algorithm first, after I confirm I get familiar with that. Then I can buy the ur5 because the price is so high
Thank you in advance!

**Comment by danielhoeltgen** [comment]
You should be able to simulate any robot that uses ros-control for its actuators in Gazebo but I dont have experience with that. Good Luck!

**Comment by AaronZhu2018** [comment]
@danielhoeltgen Thanks for your reply! I will try on that
